### ISSUE TITLE
nix-index does not disable nixpkgs overlays

### ISSUE THREAD

**Issue by lilyball** [nix-community/nix-index#161]
`nix-index` can only index packages on Hydra, but it's not disabling nixpkgs overlays when running `nix-env`. We don't want overlays as by definition anything added or modified in there isn't going to be built by Hydra, and evaluating packages in overlays can cause indexing failures (in my case a `builtins.fetchGit` that's only valid on my work computer is blocking nix-index on my home computer). This can be resolved by adding `--arg overlays '[]'` to the `nix-env` call.

**Comment by figsoda** [comment]
#221
