### ISSUE TITLE
nix-locate --help doesn't explain what the option to -t mean

### ISSUE THREAD

**Issue by ralismark** [nix-community/nix-index#204]
`nix-locate --help` includes this line for the option `--type`:
```
  -t, --type <TYPE>        Only print matches for files that have this type. If the option is given multiple times, a file will be printed if it has any of the given types [possible values: r, x, d, s]
```
however, it's not explain what each of these values mean

**Comment by bennofs** [comment]
The types mean: (r)egular file, e(x)cutable, (d)irectory, (s)ymlink

We should update the help string to explain that

**Comment by figsoda** [comment]
#220
