### ISSUE TITLE
[feat] create an online `nix-locate` service

### ISSUE THREAD

**Issue by loynoir** [nix-community/nix-index#234]

**Comment by RaitoBezarius** [comment]
search.nixos.org ?

**Comment by loynoir** [comment]
@RaitoBezarius 

- `search.nixos.org` seems not support search package using file.

- https://pkgs.alpinelinux.org/contents

**Comment by RaitoBezarius** [comment]
Then, shouldn't this be a feature request with search.nixos.org to add a /contents URL and use the locate database inside the browser?

**Comment by SuperSandro2000** [comment]
dupe of #194
